### PR TITLE
another fix for set function

### PR DESCRIPTION
**Pull request by andrewreedy**

### CODE REVIEW

**Comment by jonjamz** [comment]
Why not just use _.isEqual as it does a nested comparison?

**Comment by andrewreedy** [comment]
_.isEqual is order dependent https://www.dropbox.com/s/l9x8v11o69lu7md/Screenshot%202015-02-25%2012.48.58.png?dl=0

**Comment by jonjamz** [comment]
So if you sort an array and save it again, with the current proposed fix it won't trigger Tracker but with _.isEqual it will?

**Comment by andrewreedy** [comment]
Correct or if you just delete an element and push it back into the array and set() it, it will trigger an unneeded change. So depending on if you want order dependence.

**Comment by jonjamz** [comment]
I'm actually thinking order dependence is a good thing--if I changed the order of items in an array, I'd want that to be reflected in the DOM through a template helper, for example.

**Comment by andrewreedy** [comment]
:+1: I think so too.

**Pull request closed without merging**
